### ISSUE TITLE
when you click on the platoon game

### ISSUE THREAD

**Issue by MrPillze** [lantzelot-swe/PCUGameManager#8]
hi there

last few versions i have used contain a bug that when you click on the game platoon you get this error. it errors then makes the program useless untill you reboot it.

im on windows 11 with a 9900k and a 2080ti

thanks

java.lang.IllegalArgumentException: Does not recognize sid6541
	at se.lantz.model.SystemModel.setConfigString(SystemModel.java:294)
	at se.lantz.model.SystemModel.setConfigStringFromDb(SystemModel.java:172)
	at se.lantz.model.MainViewModel.readGameDetails(MainViewModel.java:283)
	at se.lantz.gui.GameDetailsBackgroundPanel.updateSelectedGame(GameDetailsBackgroundPanel.java:125)
	at se.lantz.gui.ListPanel.lambda$updateSelectedGame$1(ListPanel.java:453)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by lantzelot-swe** [comment]
Thanks for reporting, seems like an invalid configuration of the SID model for that game, but the manager should not break. I'll have a look.

**Comment by lantzelot-swe** [comment]
FIxed it, an invalid system config is not going to crash the manager. Saving the game again will correct the configuration in the database.

**Comment by MrPillze** [comment]
yep all good now thanks for the quick fix :) appreciated
